version: '2'
services:
  app:
    container_name: func-test
    image: func-test/app
    build: docker/nodejs
    volumes:
      - ./:/src
    env_file:
      - ./.env
    networks:
      default:
        external:
          name: guroshnet
            ipv4_address: 172.18.0.26