version: '2'
services:
  app:
    container_name: func-test
    image: func-test/app
    build: docker/nodejs
    volumes:
      - ./:/src
    env_file:
      - ./.env
    networks:
      guroshnet:
        external: true
          ipv4_address: 188.0.0.25